# Generated by Django 5.2.1 on 2025-05-13 14:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bill_consumption_m3_bill_rate_per_m3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt'),
        ),
    ]
