# Generated by Django 5.2.1 on 2025-05-13 16:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_bill_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='receipt',
        ),
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='receipt'),
        ),
    ]
